### ISSUE TITLE
[Feature request] Add source code view to Modules tab on Account page

### ISSUE THREAD

**Issue by leeduckgo** [aptos-labs/explorer#221]
For example:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/12784118/196069787-c13d49cf-d148-4795-8d75-511970cd67af.png">

**Comment by gregnazario** [comment]
Is this a request for the source code for the modules?

**Comment by leeduckgo** [comment]
> Is this a request for the source code for the modules?

Yes.

**Comment by 0xbe1** [comment]
@leeduckgo @gregnazario @jillxuu fyi this issue is addressed and can be closed

check out https://explorer.aptoslabs.com/account/0x1/modules for example

**Comment by leeduckgo** [comment]
Great!~
