### ISSUE TITLE
[Bug] Expiration time parses incorrectly when it's a really high u64 value

### ISSUE THREAD

**Issue by wanyvic** [aptos-labs/explorer#237]
version: [7602763](https://explorer.aptoslabs.com/txn/7602763)
![image](https://user-images.githubusercontent.com/26783673/197318613-6b0bf771-9169-42a8-8a90-1d009e00c4bf.png)

**Comment by gregnazario** [comment]
Yes, this is definitely wrong, since it's in seconds it should be way in the future.

**Comment by gregnazario** [comment]
This looks like time is wrapping around similar to https://github.com/aptos-labs/aptos-core/issues/3572
