### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by Khennediee** [aptos-labs/explorer#238]
when opening the aptoslabs explorer it gives an error account not found
![fsasdadsa](https://user-images.githubusercontent.com/54868053/197388125-54ef8e12-dbaf-45b5-82a4-a7dcfd3c81d5.PNG)

**Comment by vivekascoder** [comment]
Prolly because this address doesn't own the Account struct.

**Comment by gregnazario** [comment]
The account probably isn't created.  This specific one exists in every network but devnet https://explorer.aptoslabs.com/account/0xf45ca154fa8c58639b7470088e60992d7baaefd6a98154c446e2b16cf5eaf834?network=devnet
