### ISSUE TITLE
[Feature request] Support a web UI for calling smart contract functions

### ISSUE THREAD

**Issue by banool** [aptos-labs/explorer#279]
See https://github.com/aptos-labs/aptos-core/issues/5721 for the original context.

cc @poytr1

**Comment by 0xbe1** [comment]
@banool check out https://movetx.vercel.app/ - we build this at Thala Labs for admin purposes, and would love to share this with a broader community

**Comment by 0xbe1** [comment]
@jillxuu can we close this?
