### ISSUE TITLE
Please, help us interact with smart contracts. 

### ISSUE THREAD

**Issue by IgoresVer** [aptos-labs/explorer#291]
We need parameter fields:
smart contract address, function, type_arguments, arguments
and a button to generate a smart contract transaction.

**Comment by vivekascoder** [comment]
Yeah, this will be cool. Although @IgoresVer you should be able to use https://aptos-module-explorer.vercel.app/ for now.

**Comment by gregnazario** [comment]
Closing as a duplicate
