### ISSUE TITLE
[feature request] make network (devnet | testnet | mainnet) required for an explorer URL

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/explorer#323]
I propose we make the "network" (devnet | testnet | mainnet) required for an explorer URL, and here’s why.

It happens many times when people share an explorer link with me, let’s say https://explorer.aptoslabs.com/txn/0xab3e84cd0ca2aec09c6ce78ca55bcfab272204da709c73b82067c6aefc97e662

Clicking on the link shows not found. why? because my browser set the network to "testnet" by default, which is fine given I work primarily on testnet atm, however, the link that people share with me is for devnet. I know we can set `network=<devnet|testnet|mainnet>` through query params but that is not always included in the explorer URL

I wonder if it makes sense to either:
1. turn network a required query param for all routes (`/txn`, `/account`, etc), or
1. turn the network part of the route, such as `/txn` => `/<network>/txn`

I prefer (2) because it makes it easier to eyeball the network

**Comment by jillxuu** [comment]
now network param is persistent on the URL after this pr merged https://github.com/aptos-labs/explorer/pull/464
