### ISSUE TITLE
Txn Balance Change not reflecting the truth

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/explorer#439]
in this txn, balance change is blank, see https://explorer.aptoslabs.com/txn/0xe8a9cc7e974ce2c0b737241f034e76dc03c6b6e2eea2deb3538ba9c5fa18c6c6/balanceChange

however, we can tell the txn changes balance because there are a few `0x1::coin::WithdrawEvent` and `0x1::coin::DepositEvent` in https://explorer.aptoslabs.com/txn/0xe8a9cc7e974ce2c0b737241f034e76dc03c6b6e2eea2deb3538ba9c5fa18c6c6/events

**Comment by gregnazario** [comment]
It looks like it's correct now.  Closing
