### ISSUE TITLE
Operator address on delegation nodes tab is not padded with leading zeros

### ISSUE THREAD

**Issue by ruuda** [aptos-labs/explorer#480]
The “delegation nodes” tab on https://explorer.aptoslabs.com/validators/delegation?network=mainnet makes requests to `https://www.aptosnames.com/api/mainnet/v1/name/:address` to get a friendly name for the operator address. However, the address is not 0-padded to 64 hexadecimal digits.

Our operator address is `0x06bd59a049e6479b4e41352986f3a5e8241a6fe79c06431df32b42158cbe2bdc`, but the explorer makes a request for `0x6bd59a049e6479b4e41352986f3a5e8241a6fe79c06431df32b42158cbe2bdc`. We registered an ANS name and set the target address to the zero-padded `0x06bd59a049e6479b4e41352986f3a5e8241a6fe79c06431df32b42158cbe2bdc`, but then the explorer makes a query for the non-padded `0x6bd59a049e6479b4e41352986f3a5e8241a6fe79c06431df32b42158cbe2bdc` and then www.aptosnames.com returns `{}` instead of the name.

This may be a bug in the aptosnames.com API or in the explorer, but either way there is a mismatch between the two currently.

(This is an inconsistency because the staking pool address does include leading zeros.)

**Comment by jillxuu** [comment]
now issue should be fixed. closing.
