### ISSUE TITLE
Unable check infomation on the account 0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a

### ISSUE THREAD

**Issue by ghost** [aptos-labs/explorer#583]
0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a
https://explorer.aptoslabs.com/account/0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a?network=mainnet

Situation: After a loading circle, Explorer removed all infomation from indexer and removed tabs.
Expected: Remove the loading circle and prevent "remove" action at tabls and infomation from indexer.

And STOP TO make untouchable background to let us unable interact stuff before the circle timeout, that is very frustrating.

**Comment by 74891632** [comment]
Account not found

**Comment by e99243506bigplay** [comment]
> Hello @e99243506bigplay Have you resolve this issue?

Awaiting for the solution of issue now.

**Comment by 74891632** [comment]
resolved yet?

**Comment by kent-white** [comment]
looking

**Comment by kent-white** [comment]
@e99243506bigplay and @74891632 this address is and object, not an account. Not sure how you got that think but https://explorer.aptoslabs.com/object/0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a?network=mainnet is the appropriate link.

The loading issue is separate and we will look into that one.

**Comment by e99243506bigplay** [comment]
> @e99243506bigplay and @74891632 this address is and object, not an account. Not sure how you got that think but https://explorer.aptoslabs.com/object/0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a?network=mainnet is the appropriate link.
> 
> The loading issue is separate and we will look into that one.

I dont agree that "object" cant treat view to be a account, what if I execute `./aptos move run --function-id 0x1::aptos_account::create_account --gas-unit-price 100 --args address:0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a` on chain?

**Comment by gregnazario** [comment]
> > @e99243506bigplay and @74891632 this address is and object, not an account. Not sure how you got that think but https://explorer.aptoslabs.com/object/0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a?network=mainnet is the appropriate link.
> > The loading issue is separate and we will look into that one.
> 
> I dont agree that "object" cant treat view to be a account, what if I execute `./aptos move run --function-id 0x1::aptos_account::create_account --gas-unit-price 100 --args address:0x27eb09e72f97befe67d6d57a194af3ba8cad99d85b2976cbe56bb86660d1415a` on chain?
> 
> Object is basically similar to you created new address and signer pair like `0x1::account::create_resource_account` did.
> 
> Maybe there could has some account is without resources of `0x1::account::Account` or `0x1::object::ObjectCore`?

Today, data at an address must have an `0x1::account::Account` resource, or it must have had at some point `0x1::object::ObjectCore`.  They're very similar, except for this single resource (an object can actually have both, and it would show up as an account in the explorer today)

Here's an example where it won't have both, and that's only because the object resource was deleted, and the rest of it was not.
https://github.com/aptos-labs/explorer/pull/806

I haven't seen any other issues with the link you gave though, let me know if there's something else wrong.

**Comment by gregnazario** [comment]
This looks like it's been fixed with the object type.  Closing
