### ISSUE TITLE
Incorrect Balance Change in Transaction #252334139

### ISSUE THREAD

**Issue by ghost** [aptos-labs/explorer#603]
![a](https://github.com/aptos-labs/explorer/assets/113240403/e258af38-f170-41a8-a99c-7d15472d9cd1)
![a](https://github.com/aptos-labs/explorer/assets/113240403/3ddaa3e8-a351-4c25-86c9-19fe3a235a68)

**Comment by Nftness** [comment]
I believed this should change back to the original balance, have you resolve your issues yet?

**Comment by e99243506bigplay** [comment]
> I believed this should change back to the original balance, have you resolve your issues yet?

I think you didn't understand the screenshot what says. The balance changes statement on 0x...784c is displaying wrong , the transaction write set is clearly says balance after of 0x...784c is 18.00000000 APT.

**Comment by gregnazario** [comment]
It looks like the balance section has been removed from these.  I'm going to close it for now.
