### ISSUE TITLE
[UI fix] Unlock time field should be a little longer

### ISSUE THREAD

**Issue by cryptomolot** [aptos-labs/explorer#614]
If unlock time is 10 days and more the field isn't enough to show the whole date

<a href="https://ibb.co/4fyBBm3"><img src="https://i.ibb.co/pPDCC05/Unlock-time.jpg" alt="Unlock-time" border="0"></a>
<a href="https://ibb.co/ZJ56sVS"><img src="https://i.ibb.co/QcLFBfk/02-10-2023-154610.jpg" alt="02-10-2023-154610" border="0"></a><br /><a target='_blank' href='https://ru.imgbb.com/'>сайт загрузка</a><br />

p.s. 2560x1600 resolution

**Comment by cryptomolot** [comment]
hi @0xZihan

**Comment by 0xZihan** [comment]
cc @kent-white
