### ISSUE TITLE
[Question] How to use "vector<vector<u8>>" type in function argument?

### ISSUE THREAD

**Issue by swdreams** [aptos-labs/explorer#649]
I'd like to run a function: `publish_package_txn(&signer, vector<u8>, vector<vector<u8>>)`
But I don't know how to input data for `vector<vector<u8>>`type in explorer.

I mean `arg1` on https://explorer.aptoslabs.com/account/0x1/modules/run/code/publish_package_txn?network=testnet

I filed `[0x12345]`, but I've got error: CODE_DESERIALIZATION_ERROR

**Comment by Alexzander-Stone** [comment]
Developer Discussion [post #74](https://github.com/aptos-labs/aptos-developer-discussions/discussions/74#discussioncomment-8820696) goes over the proper way to supply the `vector<vector<u8>>` type on the Explorer.

If you have more questions about the various types, feel free to reach out on our [Developer Discussions page](https://github.com/aptos-labs/aptos-developer-discussions/discussions)!
