### ISSUE TITLE
[Bug] [devnet] Aptos Explorer Not Instantly Showing All User Transactions

### ISSUE THREAD

**Issue by juliaaschmidt** [aptos-labs/explorer#674]
I submitted multiple successful `publish_package_txn` on Aptos `devnet` for sender: 

f9b5c0ecd3e138e4b706983b2a30929f3e14df565c002ec1003a1afefe211999

However,  only the first `publish_package_txn` **_showed up instantly_** under the **User Transactions**:

https://explorer.aptoslabs.com/account/0xf9b5c0ecd3e138e4b706983b2a30929f3e14df565c002ec1003a1afefe211999/transactions?network=devnet

The first publish_package_tx was: 
0xa49f3ee905456d5bd5796bfeed2607f795434105c91b5402dd0c5cad0b78ac33

The subsequent transactions were successful and  had instantly reaclable transaction hashes: 

0x1468bb8c1f417881b1cbbbc3a448b8ec33020704efcde75201585b443a1f4f25
0x6e6c67a94e49b09794dafc3b02ee0d98cb07099ddeca0521f06aa1fa234fa034
0x6f068c5d51a1ab9d66083e80ee635ee8419ef2b5cf572ecdccddd282f9e3e0e0

However, they only showed up under *User Transactions* around ~10-14 mins later. 
I'm aware this hard to prove, but I experience this issue regularly.

This is only an issue for `devnet` and it impeccably quick on `testnet`. Why is that? Can you fix it?

**Comment by gregnazario** [comment]
This may be because of the differences in infra for devnet and testnet indexers.  I'm going to close this for now, but if you see it again please open a new issue.
