### ISSUE TITLE
Error messaging / content for when a network connection is not available

### ISSUE THREAD

**Issue by moonclavedev** [aptos-labs/explorer#7]
1. Choose Local from Network dropdown in header without running a Local Testnet (or within DevTools _Block Request URL_: [https://fullnode.devnet.aptoslabs.com/](url))
2. Attempt to use Explorer

Currently we don't provide any information to the user on the front-end when requests to a network are not available. This content could also be conditional based on Network Type - for example if you chose Local and the network connection fails, display a formatted error message along with relevant helper information such as providing a link to: [https://aptos.dev/tutorials/run-a-local-testnet](https://aptos.dev/tutorials/run-a-local-testnet). We should also disable search if no connection is made. 

In addition, is running Testnet / connecting to Local on a mobile or tablet device ever a possibility? If so, what are the conditions and if not - we should consider hiding the ability to choose Local on such devices, or consider this covered within the error message mentioned above.

**Comment by gregnazario** [comment]
I believe local is now hidden if it's not found.
