### ISSUE TITLE
Gas refund and net gas fee should be shown in overview

### ISSUE THREAD

**Issue by ying-w** [aptos-labs/explorer#778]
Currently, the transaction overview page shows gas units, gas fee, and gas unit price.

However, in situations where multiple resources or table items are deleted, there should be a [large storage refund](https://aptos.dev/en/network/blockchain/gas-txn-fee#calculating-storage-deletion-refund)

For these transactions, the net gas should be negative due to the refund. Please change the UX on explorer so that the refund is shown and also net gas is shown

Example: https://explorer.aptoslabs.com/txn/610075380/userTxnOverview?network=mainnet

- 29 gas units
- 150 octa per gas unit
- 4350 octa of gas used
- 86080 octa storage refund
- -81730 octa net gas

**Comment by gregnazario** [comment]
This looks like it's missing in the FA table handling for storage refunds
