### ISSUE TITLE
Search brings up address when searching for txn hash

### ISSUE THREAD

**Issue by ying-w** [aptos-labs/explorer#856]
![Screenshot 2024-10-25 at 10 42 03 AM](https://github.com/user-attachments/assets/b7ac8450-bca1-433b-bcf8-5103a8df42b8)

For the txn hash `0x9ba5990fb64c9707d1a3d621344de8b59def8dabc6de1f74395e426d2ca690af` search dropdown also shows address (but no address exists)

**Comment by gregnazario** [comment]
This is specifically for some cases where you know an address, and it has FA or tokens attached, but wasn't initialized as an account.
