### ISSUE TITLE
Remove the outdated domain from CoinMarketCap list

### ISSUE THREAD

**Issue by VladChernenko** [aptos-labs/explorer#869]
GM guys. Not a repo issue, but haven't found contacts with Aptos team via site. Decided to ping org members(@JohnChangUK , @chiumax, @GotenJBZ).

So, on CoinMarketCap domain [apscan.io](http://apscan.io) shown as one of explorer

![image](https://github.com/user-attachments/assets/7ea826c4-c099-49ab-bae9-a6c72fa3ee2b)

But IRL this domain seems to be for sale

![image](https://github.com/user-attachments/assets/68cfd9ff-515a-4851-b81f-912205f5a607)

Maybe not so serious, but probably it would be better to remove domain from CMC / your other resources(crossreferences) to avoid malicious activity.

Thanks 😺

**Comment by gregnazario** [comment]
Will forward accordingly.  Thanks!

**Comment by gregnazario** [comment]
Been removed.  Thanks!
