### ISSUE TITLE
[bug] Explorer doesn't show balance change correctly for refund

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/explorer#880]
Example: https://explorer.aptoslabs.com/txn/1857059343/balanceChange?network=mainnet

Balance change tab is correct, but the net gas change and on the main page is wrong

**Comment by 0xbe1** [comment]
@sherry-x imho it is right though?

```
Net gas change = Gas Fee - Storage Refund
```

**Comment by gregnazario** [comment]
I mean I guess here is more of a UX issue.

`-0.8` is correct, because it's a deduction of a negative number
