### ISSUE TITLE
[Bug] Lookahead shows account as an option even though hex string is only for a txn

### ISSUE THREAD

**Issue by banool** [aptos-labs/explorer#899]
# 🐛 Bug Description

If you put `0x261db5e19c0d5de2e9978c28bc7784acfda866673e9b641491f59d41fa110ec5` in the lookahead for testnet, you'll sse this:
![image](https://github.com/user-attachments/assets/d923e386-4225-41b5-a652-30015aca8292)

## How to reproduce

As above.

## Expected Behavior

Only the txn option should show since this is only a transaction.

## System information

N/A

**Comment by ying-w** [comment]
might be related to https://github.com/aptos-labs/explorer/issues/856
